### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by mastilver** [bittorrent/torrent-web-tools#4]
Hi

How do I know/install all the dependencies?
Is there is a way to install all of them, a la ruby or nodeJS?

**Comment by aqk** [comment]
Hi There,

The only dependency is python. Please let us know if you have any other questions - we're eager to improve the tool.

Adam

**Comment by mastilver** [comment]
Thank you for the quick answer.

the cli is throwing me:
`ImportError: No module named 'urlparse'`

**Comment by mastilver** [comment]
Python 3.4.3
Windows 8

**Comment by aaroncohen** [comment]
urlparse is part of the native library in Python 2.7...I think its functionality has be migrated elsewhere in Python 3, which you must be using. At some point, hopefully we'll be able to make the torrent-web-tools run on Python 3 as well, but it just hasn't been done yet.

**Comment by mastilver** [comment]
great thank you!

I will try to downgrade to 2.7

**Comment by mastilver** [comment]
And I just notice it was written on the readme... 
Sorry for that and thank you!

**Comment by aaroncohen** [comment]
You should be able to run both at the same time, you'll just specify `python27` instead of `python` at the command line.
