### ISSUE TITLE
How this works

### ISSUE THREAD

**Issue by amankumarjain** [bittorrent/torrent-web-tools#5]
Hello,
How this web tool seed any file, is it possible to download a file from this tool, How we can use this tool, actually i am planning to create a torrent client software  using python. So i am doing r&d on differnet-2 projects, please explain its working

**Comment by aaroncohen** [comment]
This tool currently only generates torrent files (.torrent). It does not seed or download.

**Comment by amankumarjain** [comment]
It means after generating torrent file, you use torrent client like(Utorrent or transmission) to seed.

**Comment by jogjayr** [comment]
Yes, that's correct. Like the README mentions, the main use of this tool is to generate torrent files for folders containing web content meant to be viewed in the [Maelstrom browser](http://project-maelstrom.bittorrent.com/). Content can be seeded using the [BitTorrent](https://www.bittorrent.com/) or [µTorrent](https://utorrent.com) clients.

If you have more questions about publishing content for Maelstrom and how Maelstrom works, I would strongly encourage you to post on the dedicated forum for it here: https://forum.bittorrent.com/forum/134-developer-discussion/ .  . I am going to close this issue now; we look forward to seeing you there.
